// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AuthLoginRequest defines model for AuthLoginRequest.
type AuthLoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// AuthRefreshRequest defines model for AuthRefreshRequest.
type AuthRefreshRequest struct {
	// RefreshToken Действующий refresh токен для обновления access токена
	RefreshToken string `json:"refreshToken"`
}

// AuthRegisterRequest defines model for AuthRegisterRequest.
type AuthRegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Nickname string              `json:"nickname"`
	Password string              `json:"password"`
}

// AuthTokens defines model for AuthTokens.
type AuthTokens struct {
	// AccessToken JWT для авторизации запросов
	AccessToken string `json:"accessToken"`

	// ExpiresIn Время жизни access токена в секундах
	ExpiresIn int `json:"expiresIn"`

	// RefreshToken Токен для обновления access токена
	RefreshToken string `json:"refreshToken"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Внутренний код ошибки
	Code    *string `json:"code,omitempty"`
	Message string  `json:"message"`
}

// MentorCard defines model for MentorCard.
type MentorCard struct {
	FullName string `json:"fullName"`
	Id       int64  `json:"id"`

	// Skills Основные технологии и направления
	Skills []string `json:"skills"`

	// Title Основная должность или позиция ментора
	Title string `json:"title"`

	// YearsOfExperience Общий стаж работы
	YearsOfExperience *int `json:"yearsOfExperience,omitempty"`
}

// MentorList defines model for MentorList.
type MentorList struct {
	Items []MentorCard `json:"items"`

	// Total Общее количество доступных менторов
	Total *int `json:"total,omitempty"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"fullName"`
	Id       int64               `json:"id"`

	// Role Роль пользователя в системе
	Role string `json:"role"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListMentorsParams defines parameters for ListMentors.
type ListMentorsParams struct {
	// Specialization Фильтр по специализации ментора
	Specialization *string `form:"specialization,omitempty" json:"specialization,omitempty"`

	// Limit Количество карточек в выдаче
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для постраничной навигации
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = AuthLoginRequest

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = AuthRefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = AuthRegisterRequest
