// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for QuestionDetailDifficulty.
const (
	Easy   QuestionDetailDifficulty = "easy"
	Hard   QuestionDetailDifficulty = "hard"
	Medium QuestionDetailDifficulty = "medium"
)

// AuthLoginRequest defines model for AuthLoginRequest.
type AuthLoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// AuthRefreshRequest defines model for AuthRefreshRequest.
type AuthRefreshRequest struct {
	// RefreshToken Действующий refresh токен для обновления access токена
	RefreshToken string `json:"refreshToken"`
}

// AuthRegisterRequest defines model for AuthRegisterRequest.
type AuthRegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Nickname string              `json:"nickname"`
	Password string              `json:"password"`
}

// AuthTokens defines model for AuthTokens.
type AuthTokens struct {
	// AccessToken JWT для авторизации запросов
	AccessToken string `json:"accessToken"`

	// ExpiresIn Время жизни access токена в секундах
	ExpiresIn int `json:"expiresIn"`

	// RefreshToken Токен для обновления access токена
	RefreshToken string `json:"refreshToken"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Внутренний код ошибки
	Code    *string `json:"code,omitempty"`
	Message string  `json:"message"`
}

// MentorCard defines model for MentorCard.
type MentorCard struct {
	FullName string `json:"fullName"`
	Id       int64  `json:"id"`

	// Skills Основные технологии и направления
	Skills []string `json:"skills"`

	// Title Основная должность или позиция ментора
	Title string `json:"title"`

	// YearsOfExperience Общий стаж работы
	YearsOfExperience *int `json:"yearsOfExperience,omitempty"`
}

// MentorList defines model for MentorList.
type MentorList struct {
	Items []MentorCard `json:"items"`

	// Total Общее количество доступных менторов
	Total *int `json:"total,omitempty"`
}

// QuestionDetail defines model for QuestionDetail.
type QuestionDetail struct {
	// Content Полный текст вопроса
	Content string `json:"content"`

	// CorrectAnswer Правильный ответ
	CorrectAnswer string `json:"correctAnswer"`

	// Difficulty Уровень сложности вопроса
	Difficulty QuestionDetailDifficulty `json:"difficulty"`

	// Explanation Объяснение правильного ответа
	Explanation *string `json:"explanation,omitempty"`
	Id          int64   `json:"id"`

	// Options Варианты ответов
	Options []string `json:"options"`

	// Technology Технология, к которой относится вопрос
	Technology string `json:"technology"`

	// Title Название вопроса
	Title string `json:"title"`
}

// QuestionDetailDifficulty Уровень сложности вопроса
type QuestionDetailDifficulty string

// QuestionList defines model for QuestionList.
type QuestionList struct {
	Items []QuestionListItem `json:"items"`

	// Total Общее количество доступных вопросов
	Total *int `json:"total,omitempty"`
}

// QuestionListItem defines model for QuestionListItem.
type QuestionListItem struct {
	Id int64 `json:"id"`

	// Technology Технология, к которой относится вопрос
	Technology string `json:"technology"`

	// Title Название вопроса
	Title string `json:"title"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"fullName"`
	Id       int64               `json:"id"`

	// Role Роль пользователя в системе
	Role string `json:"role"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListMentorsParams defines parameters for ListMentors.
type ListMentorsParams struct {
	// Specialization Фильтр по специализации ментора
	Specialization *string `form:"specialization,omitempty" json:"specialization,omitempty"`

	// Limit Количество карточек в выдаче
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для постраничной навигации
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListQuestionsParams defines parameters for ListQuestions.
type ListQuestionsParams struct {
	// Technology Фильтр по технологии
	Technology *string `form:"technology,omitempty" json:"technology,omitempty"`

	// Limit Количество вопросов в выдаче
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для постраничной навигации
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = AuthLoginRequest

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = AuthRefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = AuthRegisterRequest
