// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Выполнить вход по email и паролю
	// (POST /auth/login)
	LoginUser(ctx echo.Context) error
	// Обновить access токен по refresh токену
	// (POST /auth/refresh)
	RefreshTokens(ctx echo.Context) error
	// Зарегистрировать нового пользователя
	// (POST /auth/register)
	RegisterUser(ctx echo.Context) error
	// Получить список курсов
	// (GET /courses)
	ListCourses(ctx echo.Context, params ListCoursesParams) error
	// Создать курс
	// (POST /courses)
	CreateCourse(ctx echo.Context) error
	// Отметить модуль завершенным
	// (POST /courses/{courseId}/modules/{moduleId}/complete)
	CompleteModule(ctx echo.Context, courseId int, moduleId int) error
	// Удалить курс
	// (DELETE /courses/{id})
	DeleteCourse(ctx echo.Context, id int) error
	// Получить курс
	// (GET /courses/{id})
	GetCourseById(ctx echo.Context, id int) error
	// Обновить курс
	// (PATCH /courses/{id})
	UpdateCourse(ctx echo.Context, id int) error
	// Записаться на курс
	// (POST /courses/{id}/enroll)
	EnrollCourse(ctx echo.Context, id int) error
	// Получить модули курса
	// (GET /courses/{id}/modules)
	ListModules(ctx echo.Context, id int) error
	// Добавить модуль в курс
	// (POST /courses/{id}/modules)
	CreateModule(ctx echo.Context, id int) error
	// Удалить модуль
	// (DELETE /courses/{id}/modules/{moduleId})
	DeleteModule(ctx echo.Context, id int, moduleId int) error
	// Получить модуль
	// (GET /courses/{id}/modules/{moduleId})
	GetModuleById(ctx echo.Context, id int, moduleId int) error
	// Обновить модуль
	// (PATCH /courses/{id}/modules/{moduleId})
	UpdateModule(ctx echo.Context, id int, moduleId int) error
	// Получить вопросы модуля
	// (GET /courses/{id}/modules/{moduleId}/questions)
	ListModuleQuestions(ctx echo.Context, id int, moduleId int) error
	// Получить прогресс по курсу
	// (GET /courses/{id}/progress)
	GetCourseProgress(ctx echo.Context, id int) error
	// Получить список менторов
	// (GET /mentors)
	ListMentors(ctx echo.Context, params ListMentorsParams) error
	// Получить профиль ментора
	// (GET /mentors/{id})
	GetMentorById(ctx echo.Context, id int) error
	// Получить список всех вопросов
	// (GET /questions)
	ListQuestions(ctx echo.Context, params ListQuestionsParams) error
	// Создать вопрос
	// (POST /questions)
	CreateQuestion(ctx echo.Context) error
	// Удалить вопрос
	// (DELETE /questions/{id})
	DeleteQuestion(ctx echo.Context, id int) error
	// Получить вопрос по ID
	// (GET /questions/{id})
	GetQuestionById(ctx echo.Context, id int) error
	// Обновить вопрос
	// (PATCH /questions/{id})
	UpdateQuestion(ctx echo.Context, id int) error
	// Отправить ответ на вопрос
	// (POST /questions/{id}/submit)
	SubmitQuestionAnswer(ctx echo.Context, id int) error
	// Получить профиль текущего пользователя
	// (GET /users/me)
	GetCurrentUser(ctx echo.Context) error
	// Обновить аватар пользователя
	// (PATCH /users/me/avatar)
	UpdateUserAvatar(ctx echo.Context) error
	// Изменить пароль
	// (POST /users/me/password)
	ChangeUserPassword(ctx echo.Context) error
	// Обновить профиль пользователя
	// (PATCH /users/me/profile)
	UpdateUserProfile(ctx echo.Context) error
	// Получить общую статистику пользователя
	// (GET /users/me/statistics)
	GetUserStatistics(ctx echo.Context) error
	// Получить детальную статистику по курсам
	// (GET /users/me/statistics/courses)
	GetUserCourseStatistics(ctx echo.Context) error
	// Получить статистику по вопросам
	// (GET /users/me/statistics/questions)
	GetUserQuestionStatistics(ctx echo.Context, params GetUserQuestionStatisticsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// LoginUser converts echo context to params.
func (w *ServerInterfaceWrapper) LoginUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LoginUser(ctx)
	return err
}

// RefreshTokens converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshTokens(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshTokens(ctx)
	return err
}

// RegisterUser converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterUser(ctx)
	return err
}

// ListCourses converts echo context to params.
func (w *ServerInterfaceWrapper) ListCourses(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCoursesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListCourses(ctx, params)
	return err
}

// CreateCourse converts echo context to params.
func (w *ServerInterfaceWrapper) CreateCourse(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateCourse(ctx)
	return err
}

// CompleteModule converts echo context to params.
func (w *ServerInterfaceWrapper) CompleteModule(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", ctx.Param("courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter courseId: %s", err))
	}

	// ------------- Path parameter "moduleId" -------------
	var moduleId int

	err = runtime.BindStyledParameterWithOptions("simple", "moduleId", ctx.Param("moduleId"), &moduleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter moduleId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CompleteModule(ctx, courseId, moduleId)
	return err
}

// DeleteCourse converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCourse(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCourse(ctx, id)
	return err
}

// GetCourseById converts echo context to params.
func (w *ServerInterfaceWrapper) GetCourseById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCourseById(ctx, id)
	return err
}

// UpdateCourse converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateCourse(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateCourse(ctx, id)
	return err
}

// EnrollCourse converts echo context to params.
func (w *ServerInterfaceWrapper) EnrollCourse(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EnrollCourse(ctx, id)
	return err
}

// ListModules converts echo context to params.
func (w *ServerInterfaceWrapper) ListModules(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListModules(ctx, id)
	return err
}

// CreateModule converts echo context to params.
func (w *ServerInterfaceWrapper) CreateModule(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateModule(ctx, id)
	return err
}

// DeleteModule converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteModule(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "moduleId" -------------
	var moduleId int

	err = runtime.BindStyledParameterWithOptions("simple", "moduleId", ctx.Param("moduleId"), &moduleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter moduleId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteModule(ctx, id, moduleId)
	return err
}

// GetModuleById converts echo context to params.
func (w *ServerInterfaceWrapper) GetModuleById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "moduleId" -------------
	var moduleId int

	err = runtime.BindStyledParameterWithOptions("simple", "moduleId", ctx.Param("moduleId"), &moduleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter moduleId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetModuleById(ctx, id, moduleId)
	return err
}

// UpdateModule converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateModule(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "moduleId" -------------
	var moduleId int

	err = runtime.BindStyledParameterWithOptions("simple", "moduleId", ctx.Param("moduleId"), &moduleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter moduleId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateModule(ctx, id, moduleId)
	return err
}

// ListModuleQuestions converts echo context to params.
func (w *ServerInterfaceWrapper) ListModuleQuestions(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "moduleId" -------------
	var moduleId int

	err = runtime.BindStyledParameterWithOptions("simple", "moduleId", ctx.Param("moduleId"), &moduleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter moduleId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListModuleQuestions(ctx, id, moduleId)
	return err
}

// GetCourseProgress converts echo context to params.
func (w *ServerInterfaceWrapper) GetCourseProgress(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCourseProgress(ctx, id)
	return err
}

// ListMentors converts echo context to params.
func (w *ServerInterfaceWrapper) ListMentors(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMentorsParams
	// ------------- Optional query parameter "specialization" -------------

	err = runtime.BindQueryParameter("form", true, false, "specialization", ctx.QueryParams(), &params.Specialization)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter specialization: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListMentors(ctx, params)
	return err
}

// GetMentorById converts echo context to params.
func (w *ServerInterfaceWrapper) GetMentorById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMentorById(ctx, id)
	return err
}

// ListQuestions converts echo context to params.
func (w *ServerInterfaceWrapper) ListQuestions(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListQuestionsParams
	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "technology" -------------

	err = runtime.BindQueryParameter("form", true, false, "technology", ctx.QueryParams(), &params.Technology)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter technology: %s", err))
	}

	// ------------- Optional query parameter "difficulty" -------------

	err = runtime.BindQueryParameter("form", true, false, "difficulty", ctx.QueryParams(), &params.Difficulty)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter difficulty: %s", err))
	}

	// ------------- Optional query parameter "company" -------------

	err = runtime.BindQueryParameter("form", true, false, "company", ctx.QueryParams(), &params.Company)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter company: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListQuestions(ctx, params)
	return err
}

// CreateQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) CreateQuestion(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateQuestion(ctx)
	return err
}

// DeleteQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteQuestion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteQuestion(ctx, id)
	return err
}

// GetQuestionById converts echo context to params.
func (w *ServerInterfaceWrapper) GetQuestionById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetQuestionById(ctx, id)
	return err
}

// UpdateQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateQuestion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateQuestion(ctx, id)
	return err
}

// SubmitQuestionAnswer converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitQuestionAnswer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitQuestionAnswer(ctx, id)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// UpdateUserAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserAvatar(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserAvatar(ctx)
	return err
}

// ChangeUserPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ChangeUserPassword(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ChangeUserPassword(ctx)
	return err
}

// UpdateUserProfile converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserProfile(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserProfile(ctx)
	return err
}

// GetUserStatistics converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserStatistics(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserStatistics(ctx)
	return err
}

// GetUserCourseStatistics converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserCourseStatistics(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserCourseStatistics(ctx)
	return err
}

// GetUserQuestionStatistics converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserQuestionStatistics(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserQuestionStatisticsParams
	// ------------- Optional query parameter "courseId" -------------

	err = runtime.BindQueryParameter("form", true, false, "courseId", ctx.QueryParams(), &params.CourseId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter courseId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserQuestionStatistics(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/auth/login", wrapper.LoginUser)
	router.POST(baseURL+"/auth/refresh", wrapper.RefreshTokens)
	router.POST(baseURL+"/auth/register", wrapper.RegisterUser)
	router.GET(baseURL+"/courses", wrapper.ListCourses)
	router.POST(baseURL+"/courses", wrapper.CreateCourse)
	router.POST(baseURL+"/courses/:courseId/modules/:moduleId/complete", wrapper.CompleteModule)
	router.DELETE(baseURL+"/courses/:id", wrapper.DeleteCourse)
	router.GET(baseURL+"/courses/:id", wrapper.GetCourseById)
	router.PATCH(baseURL+"/courses/:id", wrapper.UpdateCourse)
	router.POST(baseURL+"/courses/:id/enroll", wrapper.EnrollCourse)
	router.GET(baseURL+"/courses/:id/modules", wrapper.ListModules)
	router.POST(baseURL+"/courses/:id/modules", wrapper.CreateModule)
	router.DELETE(baseURL+"/courses/:id/modules/:moduleId", wrapper.DeleteModule)
	router.GET(baseURL+"/courses/:id/modules/:moduleId", wrapper.GetModuleById)
	router.PATCH(baseURL+"/courses/:id/modules/:moduleId", wrapper.UpdateModule)
	router.GET(baseURL+"/courses/:id/modules/:moduleId/questions", wrapper.ListModuleQuestions)
	router.GET(baseURL+"/courses/:id/progress", wrapper.GetCourseProgress)
	router.GET(baseURL+"/mentors", wrapper.ListMentors)
	router.GET(baseURL+"/mentors/:id", wrapper.GetMentorById)
	router.GET(baseURL+"/questions", wrapper.ListQuestions)
	router.POST(baseURL+"/questions", wrapper.CreateQuestion)
	router.DELETE(baseURL+"/questions/:id", wrapper.DeleteQuestion)
	router.GET(baseURL+"/questions/:id", wrapper.GetQuestionById)
	router.PATCH(baseURL+"/questions/:id", wrapper.UpdateQuestion)
	router.POST(baseURL+"/questions/:id/submit", wrapper.SubmitQuestionAnswer)
	router.GET(baseURL+"/users/me", wrapper.GetCurrentUser)
	router.PATCH(baseURL+"/users/me/avatar", wrapper.UpdateUserAvatar)
	router.POST(baseURL+"/users/me/password", wrapper.ChangeUserPassword)
	router.PATCH(baseURL+"/users/me/profile", wrapper.UpdateUserProfile)
	router.GET(baseURL+"/users/me/statistics", wrapper.GetUserStatistics)
	router.GET(baseURL+"/users/me/statistics/courses", wrapper.GetUserCourseStatistics)
	router.GET(baseURL+"/users/me/statistics/questions", wrapper.GetUserQuestionStatistics)

}
