// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for QuestionCreateRequestDifficulty.
const (
	QuestionCreateRequestDifficultyEasy   QuestionCreateRequestDifficulty = "easy"
	QuestionCreateRequestDifficultyHard   QuestionCreateRequestDifficulty = "hard"
	QuestionCreateRequestDifficultyMedium QuestionCreateRequestDifficulty = "medium"
)

// Defines values for QuestionDetailDifficulty.
const (
	QuestionDetailDifficultyEasy   QuestionDetailDifficulty = "easy"
	QuestionDetailDifficultyHard   QuestionDetailDifficulty = "hard"
	QuestionDetailDifficultyMedium QuestionDetailDifficulty = "medium"
)

// Defines values for QuestionUpdateRequestDifficulty.
const (
	Easy   QuestionUpdateRequestDifficulty = "easy"
	Hard   QuestionUpdateRequestDifficulty = "hard"
	Medium QuestionUpdateRequestDifficulty = "medium"
)

// AuthLoginRequest defines model for AuthLoginRequest.
type AuthLoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// AuthRefreshRequest defines model for AuthRefreshRequest.
type AuthRefreshRequest struct {
	// RefreshToken Действующий refresh токен для обновления access токена
	RefreshToken string `json:"refreshToken"`
}

// AuthRegisterRequest defines model for AuthRegisterRequest.
type AuthRegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Nickname string              `json:"nickname"`
	Password string              `json:"password"`
}

// AuthTokens defines model for AuthTokens.
type AuthTokens struct {
	// AccessToken JWT для авторизации запросов
	AccessToken string `json:"accessToken"`

	// ExpiresIn Время жизни access токена в секундах
	ExpiresIn int `json:"expiresIn"`

	// RefreshToken Токен для обновления access токена
	RefreshToken string `json:"refreshToken"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	NewPassword string `json:"newPassword"`
	OldPassword string `json:"oldPassword"`
}

// CourseCreateRequest defines model for CourseCreateRequest.
type CourseCreateRequest struct {
	Description string `json:"description"`
	IsPublished *bool  `json:"isPublished,omitempty"`
	Title       string `json:"title"`
}

// CourseDetail defines model for CourseDetail.
type CourseDetail struct {
	Description string         `json:"description"`
	Id          int            `json:"id"`
	IsPublished bool           `json:"isPublished"`
	Modules     []ModuleDetail `json:"modules"`
	Title       string         `json:"title"`
}

// CourseList defines model for CourseList.
type CourseList struct {
	Items []CourseListItem `json:"items"`
	Total *int             `json:"total,omitempty"`
}

// CourseListItem defines model for CourseListItem.
type CourseListItem struct {
	Description string `json:"description"`
	Id          int    `json:"id"`
	IsPublished bool   `json:"isPublished"`
	Title       string `json:"title"`
}

// CourseProgress defines model for CourseProgress.
type CourseProgress struct {
	CompletedModules int                   `json:"completedModules"`
	CourseId         int                   `json:"courseId"`
	Modules          *[]ModuleProgressItem `json:"modules,omitempty"`
	Percentage       *float32              `json:"percentage,omitempty"`
	TotalModules     int                   `json:"totalModules"`
}

// CourseUpdateRequest defines model for CourseUpdateRequest.
type CourseUpdateRequest struct {
	Description *string `json:"description,omitempty"`
	IsPublished *bool   `json:"isPublished,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// EnrollmentStatus defines model for EnrollmentStatus.
type EnrollmentStatus struct {
	CourseId   int        `json:"courseId"`
	Enrolled   bool       `json:"enrolled"`
	EnrolledAt *time.Time `json:"enrolledAt,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Внутренний код ошибки
	Code    *string `json:"code,omitempty"`
	Message string  `json:"message"`
}

// MentorCard defines model for MentorCard.
type MentorCard struct {
	FullName string `json:"fullName"`
	Id       int    `json:"id"`

	// Skills Основные технологии и направления
	Skills []string `json:"skills"`

	// Title Основная должность или позиция ментора
	Title string `json:"title"`

	// YearsOfExperience Общий стаж работы
	YearsOfExperience *int `json:"yearsOfExperience,omitempty"`
}

// MentorList defines model for MentorList.
type MentorList struct {
	Items []MentorCard `json:"items"`

	// Total Общее количество доступных менторов
	Total *int `json:"total,omitempty"`
}

// MentorProfile defines model for MentorProfile.
type MentorProfile struct {
	Contacts        *map[string]interface{} `json:"contacts,omitempty"`
	Description     *string                 `json:"description,omitempty"`
	ExperienceYears *int                    `json:"experienceYears,omitempty"`
	Grade           *string                 `json:"grade,omitempty"`
	Id              int                     `json:"id"`
	Pricelist       *map[string]interface{} `json:"pricelist,omitempty"`
	Specialization  string                  `json:"specialization"`
	Tags            *[]string               `json:"tags,omitempty"`
	UserId          int                     `json:"userId"`
}

// ModuleCompletion defines model for ModuleCompletion.
type ModuleCompletion struct {
	Completed   bool       `json:"completed"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	CourseId    int        `json:"courseId"`
	ModuleId    int        `json:"moduleId"`
}

// ModuleCreateRequest defines model for ModuleCreateRequest.
type ModuleCreateRequest struct {
	Content     *string `json:"content,omitempty"`
	Description string  `json:"description"`
	Order       int     `json:"order"`
	Title       string  `json:"title"`
}

// ModuleDetail defines model for ModuleDetail.
type ModuleDetail struct {
	// Content Текст/markdown модуля
	Content     *string `json:"content,omitempty"`
	Description string  `json:"description"`
	Id          int     `json:"id"`
	Order       int     `json:"order"`
	Title       string  `json:"title"`
}

// ModuleList defines model for ModuleList.
type ModuleList struct {
	Items []ModuleDetail `json:"items"`
}

// ModuleProgressItem defines model for ModuleProgressItem.
type ModuleProgressItem struct {
	Completed   bool       `json:"completed"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	ModuleId    int        `json:"moduleId"`
	Title       string     `json:"title"`
}

// ModuleUpdateRequest defines model for ModuleUpdateRequest.
type ModuleUpdateRequest struct {
	Content     *string `json:"content,omitempty"`
	Description *string `json:"description,omitempty"`
	Order       *int    `json:"order,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// QuestionCreateRequest defines model for QuestionCreateRequest.
type QuestionCreateRequest struct {
	Content       string                          `json:"content"`
	CorrectAnswer string                          `json:"correctAnswer"`
	Difficulty    QuestionCreateRequestDifficulty `json:"difficulty"`
	Explanation   *string                         `json:"explanation,omitempty"`
	Options       []string                        `json:"options"`
	Tags          *[]string                       `json:"tags,omitempty"`
	Technology    string                          `json:"technology"`
	Title         string                          `json:"title"`
}

// QuestionCreateRequestDifficulty defines model for QuestionCreateRequest.Difficulty.
type QuestionCreateRequestDifficulty string

// QuestionDetail defines model for QuestionDetail.
type QuestionDetail struct {
	// Content Полный текст вопроса
	Content string `json:"content"`

	// CorrectAnswer Правильный ответ
	CorrectAnswer string `json:"correctAnswer"`

	// Difficulty Уровень сложности вопроса
	Difficulty QuestionDetailDifficulty `json:"difficulty"`

	// Explanation Объяснение правильного ответа
	Explanation *string `json:"explanation,omitempty"`
	Id          int     `json:"id"`

	// Options Варианты ответов
	Options []string `json:"options"`

	// Tags Теги/метки вопроса
	Tags *[]string `json:"tags,omitempty"`

	// Technology Технология, к которой относится вопрос
	Technology string `json:"technology"`

	// Title Название вопроса
	Title string `json:"title"`
}

// QuestionDetailDifficulty Уровень сложности вопроса
type QuestionDetailDifficulty string

// QuestionList defines model for QuestionList.
type QuestionList struct {
	Items []QuestionListItem `json:"items"`

	// Total Общее количество доступных вопросов
	Total *int `json:"total,omitempty"`
}

// QuestionListItem defines model for QuestionListItem.
type QuestionListItem struct {
	Id int `json:"id"`

	// Technology Технология, к которой относится вопрос
	Technology string `json:"technology"`

	// Title Название вопроса
	Title string `json:"title"`
}

// QuestionStatisticsByCourse defines model for QuestionStatisticsByCourse.
type QuestionStatisticsByCourse struct {
	CourseId    int                       `json:"courseId"`
	CourseTitle string                    `json:"courseTitle"`
	Statistics  QuestionStatisticsSummary `json:"statistics"`
}

// QuestionStatisticsSummary defines model for QuestionStatisticsSummary.
type QuestionStatisticsSummary struct {
	// AvgTimeSpent Среднее время на вопрос в секундах
	AvgTimeSpent float32 `json:"avgTimeSpent"`

	// CorrectAnswersPct Процент правильных ответов
	CorrectAnswersPct float32 `json:"correctAnswersPct"`

	// TotalAttempts Общее количество попыток
	TotalAttempts int `json:"totalAttempts"`

	// TotalSolved Всего решено вопросов
	TotalSolved int `json:"totalSolved"`
}

// QuestionUpdateRequest defines model for QuestionUpdateRequest.
type QuestionUpdateRequest struct {
	Content       *string                          `json:"content,omitempty"`
	CorrectAnswer *string                          `json:"correctAnswer,omitempty"`
	Difficulty    *QuestionUpdateRequestDifficulty `json:"difficulty,omitempty"`
	Explanation   *string                          `json:"explanation,omitempty"`
	Options       *[]string                        `json:"options,omitempty"`
	Tags          *[]string                        `json:"tags,omitempty"`
	Technology    *string                          `json:"technology,omitempty"`
	Title         *string                          `json:"title,omitempty"`
}

// QuestionUpdateRequestDifficulty defines model for QuestionUpdateRequest.Difficulty.
type QuestionUpdateRequestDifficulty string

// UserAvatarResponse defines model for UserAvatarResponse.
type UserAvatarResponse struct {
	AvatarUrl string `json:"avatarUrl"`
}

// UserAvatarUpdateRequest defines model for UserAvatarUpdateRequest.
type UserAvatarUpdateRequest struct {
	// AvatarUrl HTTP/HTTPS URL аватара пользователя
	AvatarUrl string `json:"avatarUrl"`
}

// UserCourseStatisticsItem defines model for UserCourseStatisticsItem.
type UserCourseStatisticsItem struct {
	CompletedModules int       `json:"completedModules"`
	CourseId         int       `json:"courseId"`
	CourseTitle      string    `json:"courseTitle"`
	ProgressPct      float32   `json:"progressPct"`
	StartedAt        time.Time `json:"startedAt"`

	// TimeSpent Общее время обучения в часах
	TimeSpent    *float32 `json:"timeSpent,omitempty"`
	TotalModules int      `json:"totalModules"`
}

// UserCourseStatisticsList defines model for UserCourseStatisticsList.
type UserCourseStatisticsList struct {
	Items []UserCourseStatisticsItem `json:"items"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"fullName"`
	Id       int                 `json:"id"`

	// Role Роль пользователя в системе
	Role string `json:"role"`
}

// UserProfileUpdateRequest defines model for UserProfileUpdateRequest.
type UserProfileUpdateRequest struct {
	Description *string              `json:"description,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Name        *string              `json:"name,omitempty"`
	Username    *string              `json:"username,omitempty"`
}

// UserProfileUpdateResponse defines model for UserProfileUpdateResponse.
type UserProfileUpdateResponse struct {
	Profile UserProfile `json:"profile"`
	Tokens  *AuthTokens `json:"tokens,omitempty"`
}

// UserQuestionStatistics defines model for UserQuestionStatistics.
type UserQuestionStatistics struct {
	ByCourse []QuestionStatisticsByCourse `json:"byCourse"`
	Overall  QuestionStatisticsSummary    `json:"overall"`
}

// UserStatistics defines model for UserStatistics.
type UserStatistics struct {
	// CoursesCompleted Количество завершенных курсов
	CoursesCompleted int `json:"coursesCompleted"`

	// CoursesEnrolled Количество записанных курсов
	CoursesEnrolled int `json:"coursesEnrolled"`

	// OverallProgressPct Общий процент прогресса
	OverallProgressPct  float32                   `json:"overallProgressPct"`
	QuestionsStatistics QuestionStatisticsSummary `json:"questionsStatistics"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListCoursesParams defines parameters for ListCourses.
type ListCoursesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListMentorsParams defines parameters for ListMentors.
type ListMentorsParams struct {
	// Specialization Фильтр по специализации ментора
	Specialization *string `form:"specialization,omitempty" json:"specialization,omitempty"`

	// Limit Количество карточек в выдаче
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для постраничной навигации
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListQuestionsParams defines parameters for ListQuestions.
type ListQuestionsParams struct {
	// Technology Фильтр по технологии
	Technology *string `form:"technology,omitempty" json:"technology,omitempty"`

	// Limit Количество вопросов в выдаче
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для постраничной навигации
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetUserQuestionStatisticsParams defines parameters for GetUserQuestionStatistics.
type GetUserQuestionStatisticsParams struct {
	// CourseId Фильтр по курсу (опционально)
	CourseId *int `form:"courseId,omitempty" json:"courseId,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = AuthLoginRequest

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = AuthRefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = AuthRegisterRequest

// CreateCourseJSONRequestBody defines body for CreateCourse for application/json ContentType.
type CreateCourseJSONRequestBody = CourseCreateRequest

// UpdateCourseJSONRequestBody defines body for UpdateCourse for application/json ContentType.
type UpdateCourseJSONRequestBody = CourseUpdateRequest

// CreateModuleJSONRequestBody defines body for CreateModule for application/json ContentType.
type CreateModuleJSONRequestBody = ModuleCreateRequest

// UpdateModuleJSONRequestBody defines body for UpdateModule for application/json ContentType.
type UpdateModuleJSONRequestBody = ModuleUpdateRequest

// CreateQuestionJSONRequestBody defines body for CreateQuestion for application/json ContentType.
type CreateQuestionJSONRequestBody = QuestionCreateRequest

// UpdateQuestionJSONRequestBody defines body for UpdateQuestion for application/json ContentType.
type UpdateQuestionJSONRequestBody = QuestionUpdateRequest

// UpdateUserAvatarJSONRequestBody defines body for UpdateUserAvatar for application/json ContentType.
type UpdateUserAvatarJSONRequestBody = UserAvatarUpdateRequest

// ChangeUserPasswordJSONRequestBody defines body for ChangeUserPassword for application/json ContentType.
type ChangeUserPasswordJSONRequestBody = ChangePasswordRequest

// UpdateUserProfileJSONRequestBody defines body for UpdateUserProfile for application/json ContentType.
type UpdateUserProfileJSONRequestBody = UserProfileUpdateRequest
